// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6dook3vUoHloFC0eWsBN218e-YlvbZ50',
    appId: '1:994177180374:web:8810f5a6d73371c49ddf77',
    messagingSenderId: '994177180374',
    projectId: 'dpapp-70c5f',
    authDomain: 'dpapp-70c5f.firebaseapp.com',
    databaseURL: 'https://dpapp-70c5f-default-rtdb.firebaseio.com',
    storageBucket: 'dpapp-70c5f.appspot.com',
    measurementId: 'G-Q44B657GCW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj-ppsMbxgMh3p5wAx3sUit6ecNyy9m0U',
    appId: '1:994177180374:android:7872e36683ce086d9ddf77',
    messagingSenderId: '994177180374',
    projectId: 'dpapp-70c5f',
    databaseURL: 'https://dpapp-70c5f-default-rtdb.firebaseio.com',
    storageBucket: 'dpapp-70c5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb2OglinEzBGuBFVpd0LxEv3RIMHebJTE',
    appId: '1:994177180374:ios:9501047e624541d29ddf77',
    messagingSenderId: '994177180374',
    projectId: 'dpapp-70c5f',
    databaseURL: 'https://dpapp-70c5f-default-rtdb.firebaseio.com',
    storageBucket: 'dpapp-70c5f.appspot.com',
    iosBundleId: 'com.example.locationSharingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAb2OglinEzBGuBFVpd0LxEv3RIMHebJTE',
    appId: '1:994177180374:ios:9501047e624541d29ddf77',
    messagingSenderId: '994177180374',
    projectId: 'dpapp-70c5f',
    databaseURL: 'https://dpapp-70c5f-default-rtdb.firebaseio.com',
    storageBucket: 'dpapp-70c5f.appspot.com',
    iosBundleId: 'com.example.locationSharingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6dook3vUoHloFC0eWsBN218e-YlvbZ50',
    appId: '1:994177180374:web:f6e2c7680d4706609ddf77',
    messagingSenderId: '994177180374',
    projectId: 'dpapp-70c5f',
    authDomain: 'dpapp-70c5f.firebaseapp.com',
    databaseURL: 'https://dpapp-70c5f-default-rtdb.firebaseio.com',
    storageBucket: 'dpapp-70c5f.appspot.com',
    measurementId: 'G-5QRQFPREJM',
  );
}
